const $ = s => document.querySelector(s);
const fields = ['idea','audience','type','time','goal','constraint'];
const key = 'launchpack/current/v1';
let activePlaybook = 'challenge';
let currentMarkdown = '';
const examples = {
  idea:'A zero-budget Roblox action game where players train timing, dodges, parries, and combos through short challenge rooms.',
  audience:'Roblox players who want to get better at action combat', type:'game', time:'14 days', goal:'portfolio proof', constraint:'solo dev, free assets only, needs to feel fun fast'
};
function clean(s,fallback){return (s||'').trim() || fallback}
function mvpFor(type, idea){const map={game:['One playable core loop','Three escalating challenge levels','A simple score/rank screen','One shareable clip moment'],portfolio:['One case-study homepage','Three proof cards','A process section','A contact/next-step CTA'],'content series':['A named series promise','Five episode outlines','A posting schedule','One reusable thumbnail/caption format'],community:['A landing page','A starter discussion prompt','A code of conduct','A first-event plan'],'app/tool':['One input-to-output workflow','Saved local state','Export/share button','A focused landing section']};return map[type]||map['app/tool']}
function playbookLine(playbook,audience){return {challenge:`Publicly ship a daily build log for ${audience}; make the countdown the story.`,beforeafter:`Lead with the painful before-state, then show the clean after-state in under 10 seconds.`,freeutility:`Give away the smallest useful version first, then invite people to request improvements.`,story:`Explain why this exists in one human sentence, then show the build in motion.`}[playbook]}
function generate(){const data=Object.fromEntries(fields.map(id=>[id,clean($('#'+id).value, id==='audience'?'people with the problem':id==='constraint'?'limited time and budget':'') ])); if(!data.idea){return null} const mvp=mvpFor(data.type,data.idea); const words=data.idea.toLowerCase(); let novelty=55+(data.audience.length>18?10:0)+(data.constraint.length>12?10:0)+(data.goal.includes('attention')?8:0)+(words.includes('roblox')||words.includes('ai')||words.includes('free')?7:0); novelty=Math.max(18,Math.min(96,novelty)); const hook=playbookLine(activePlaybook,data.audience); const title=data.idea.split(/[.,]/)[0].replace(/^a\s+/i,'').slice(0,76); const roadmap=data.time==='weekend'?['Hour 1: choose one user and one promise','Hours 2-5: build the smallest demo','Hour 6: make it understandable without explanation','Hour 7: record proof','Hour 8: publish and ask for feedback']:['Day 1: lock the promise and MVP','Day 2-4: build core loop','Day 5: test with one real person','Day 6: add proof, copy, and polish','Day 7: publish, post, and collect feedback']; const post=`I’m building ${title}. It is for ${data.audience}. The constraint: ${data.constraint}. The goal this week: ship a tiny version people can actually try. Want the first link?`; currentMarkdown=`# LaunchPack: ${title}\n\n## Audience\n${data.audience}\n\n## Hook\n${hook}\n\n## MVP\n${mvp.map(x=>'- '+x).join('\n')}\n\n## Roadmap\n${roadmap.map(x=>'- '+x).join('\n')}\n\n## Launch post\n${post}\n\n## Next action\nCreate the first visible demo screen and share a 10-second proof clip.\n`; $('#pack').innerHTML=`<div class="pack-head"><div><span class="pill">${data.type} • ${data.time}</span><h3>${escapeHtml(title)}</h3></div><span class="pill">${data.goal}</span></div><section class="pack-section"><h4>Attention hook</h4><p>${escapeHtml(hook)}</p></section><section class="pack-section"><h4>MVP scope</h4><ul>${mvp.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></section><section class="pack-section"><h4>Build roadmap</h4><ul>${roadmap.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></section><section class="pack-section"><h4>Launch post</h4><p>${escapeHtml(post)}</p></section><section class="pack-section"><h4>Next action</h4><p>Create the first visible demo screen and share a 10-second proof clip.</p></section>`; setScore(novelty, data); localStorage.setItem(key,JSON.stringify({...data,activePlaybook,currentMarkdown})); return true}
function setScore(score,data){$('#scoreValue').textContent=score; $('#scoreRing').style.background=`conic-gradient(var(--green) ${score*3.6}deg,var(--line) 0deg)`; $('#scoreText').textContent=score>78?`Strong. Your audience, constraint, and goal are specific enough to launch.`:score>55?`Good start. Make the audience and proof moment sharper before posting.`:`Too vague. Narrow the audience and define one proof moment.`}
function loadDemo(){for(const [k,v] of Object.entries(examples)) $('#'+k).value=v; activePlaybook='challenge'; setActive(); generate(); location.hash='builder'}
function setActive(){document.querySelectorAll('.playbook').forEach(b=>b.classList.toggle('active',b.dataset.playbook===activePlaybook))}
function copyPack(){if(!currentMarkdown) generate(); navigator.clipboard?.writeText(currentMarkdown); $('#copyBtn').textContent='Copied ✓'; setTimeout(()=>$('#copyBtn').textContent='Copy LaunchPack',1300)}
function downloadPack(){if(!currentMarkdown) generate(); const blob=new Blob([currentMarkdown],{type:'text/markdown'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='launchpack.md'; a.click(); URL.revokeObjectURL(url)}
function restore(){try{const d=JSON.parse(localStorage.getItem(key)||'null'); if(!d)return; fields.forEach(id=>{if(d[id]) $('#'+id).value=d[id]}); activePlaybook=d.activePlaybook||'challenge'; setActive(); generate()}catch{}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#launchForm').addEventListener('submit',e=>{e.preventDefault(); generate()}); $('#demoBtn').addEventListener('click',loadDemo); $('#copyBtn').addEventListener('click',copyPack); $('#downloadBtn').addEventListener('click',downloadPack); $('#clearBtn').addEventListener('click',()=>{localStorage.removeItem(key); fields.forEach(id=>$('#'+id).value=''); currentMarkdown=''; $('#pack').innerHTML='<div class="empty"><strong>Your LaunchPack appears here.</strong><p>It will include MVP, hook, roadmap, copy, launch checklist, and next action.</p></div>'; setScore(0,{})}); document.querySelectorAll('.playbook').forEach(b=>b.addEventListener('click',()=>{activePlaybook=b.dataset.playbook; setActive(); generate()})); restore();
